### ISSUE TITLE
When use.descriptions=TRUE,  these are not applied on the compensation matrix names too

### ISSUE THREAD

**Issue by makostadima** [tercen/read_fcs_operator#12]
At the moment when reading an FCS file (v 1.5.1) and setting use.descriptions=TRUE, only the headers of the raw values matrix are set and not the ones in the compensation matrix, creating an incosistency when trying to run the compensate_FCS_operator.

**Comment by agouy** [comment]
Fixed in 1.6.0 - uses channel "names" systematically in both FCS and compensation output + an annotation file is created containing descriptions
