### ISSUE TITLE
FlowJo Tutorial data not uploading on tercen when selecting the built-in compensation matrix setting

### ISSUE THREAD

**Issue by makostadima** [tercen/read_fcs_operator#6]
@MahoNagasawa and I have been trying to recreate her FlowJo manual gating strategy on Tercen. For this purpose we're trying to use the FlowJo Tutorial Dataset found [here](https://drive.google.com/drive/folders/1Q3lfJUsprZebV421ec9DXrCcr-O7RkxX).

When trying to upload **LD1_NS+NS_A01_exp.fcs** using this operator (v1.3.1) and setting the _use.builtin.compensation_ I get the following error: 

> Failed to run operator, exit code = 1 --ERR-- WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. Error in read_fcs(filename, comp.use, c.names, which.lines, separator) : Different number of columns between FCS file and compensation matrix. Compensation cannot be applied. Calls: %>% ... lapply -> bind_rows -> list2 -> lapply -> FUN -> read_fcs In addition: Warning messages: 1: In readFCSdata(con, offsets, txt, transformation, which.lines, scale, : Some data values of 'AARD-A' channel exceed its $PnR value 82897 and will be truncated! To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE' 2: In readFCSdata(con, offsets, txt, transformation, which.lines, scale, : Some data values of 'APC-H7-A' channel exceed its $PnR value 82897 and will be truncated! To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE' 3: In readFCSdata(con, offsets, txt, transformation, which.lines, scale, : Some data values of 'Ax488-A' channel exceed its $PnR value 82897 and will be truncated! To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE' 4: In readFCSdata(con, offsets, txt, transformation, which.lines, scale, : Some data values of 'Ax700-A' channel exceed its $PnR value 82897 and will be truncated! To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE' 5: In readFCSdata(con, offsets, txt, transformation, which.lines, scale, : Some data values of 'PE-A' channel exceed its $PnR value 82897 and will be truncated! To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE' 6: In readFCSdata(con, offsets, txt, transformation, which.lines, scale, : Some data values of 'PE-Cy5-A' channel exceed its $PnR value 82897 and will be truncated! To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE' 7: In readFCSdata(con, offsets, txt, transformation, which.lines, scale, : Some data values of 'PE-Cy7-A' channel exceed its $PnR value 82897 and will be truncated! To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE' 8: In readFCSdata(con, offsets, txt, transformation, which.lines, scale, : Some data values of 'PE-TxRed-A' channel exceed its $PnR value 82897 and will be truncated! To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE' 9: In readFCSdata(con, offsets, txt, transformation, which.lines, scale, : Some data values of 'PacBlue-A' channel exceed its $PnR value 82897 and will be truncated! To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE' 10: In readFCSdata(con, offsets, txt, transformation, which.lines, scale, : Some data values of 'Time' channel exceed its $PnR value 0 and will be truncated! To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE' Execution halted

So I ended up running it without this setting and I succesfully uploaded the dataset. When comparing it though with the one exported from FlowJo I can see that the values aren't identical and that FlowJo has compensated the data: https://tercen.com/Maho_Team/w/75ee4825c08b83cacbe922291eac834f/ds/b44029f7-7200-40e7-962c-6d1ecac89937

My questions here are:

- does the FCS file contain a builtin compensation matrix?
- If yes, why our operator can't read it and apply it?
- If no, what compensation matrix does FlowJo apply to the data? Is it the Auto-spill-calculated one?

**Comment by lucaslelann** [comment]
Hello,

The FCS contains a builtin compensation matrix.
Our operator can't read it because there is a column named "blank" which contain values but is not found in the compensation matrix found inside the file.

**Comment by makostadima** [comment]
I see. Thanks @lucaslelann for looking into this.

@agouy in my opinion this is one of the datasets that kind of have to work on Tercen, meaning that it needs to be able to be loaded and compensated no matter what. I know hardcoded solutions here aren't ideal, but we may have to come up with something. What do you think?

**Comment by agouy** [comment]
@lucaslelann has implemented the hardcoded fix in 1.3.3, we'll implement a cleaner way of doing later. @makostadima Let us know if you're still having the issue

**Comment by MahoNagasawa** [comment]
@makostadima @lucaslelann @agouy 
it looks like 1.3.3 is working :-) (I just need to remember to change the setting use.builtin.compensation, should it be default?)
https://tercen.com/Maho_Team/p/e0712fdd6b5afcdf8fef72f892e4deb1

thank you!

**Comment by agouy** [comment]
@MahoNagasawa great news! We won't do compensation by default for now as ultimately this will be done using a separate operator.
