### ISSUE TITLE
When Time isn't set, there's no factor to define the different observations for the following compensation to work

### ISSUE THREAD

**Issue by makostadima** [tercen/read_fcs_operator#7]
Example: https://tercen.com/myrto.kostadima/w/41fcacecf20de12dea7c2421179d27ca/ds/ed53ade5-d828-4c01-be53-074b4c2ee5d3

In the FlowJo plugin template workflows we used the row_id instead to define the different events/observations. Probably some similar approach should be taken here. Otherwise, I cannot apply the compensation on the data.

**Comment by makostadima** [comment]
@agouy pointed out that the rowId factor is generated when the data is uploaded through the __New data set__ button on the project page.

I tried uploading the data this way and I got the following error:

![image](https://user-images.githubusercontent.com/1746464/199193743-7677bcf1-274e-4813-929c-ed92037df221.png)

You can download the data from [here](https://drive.google.com/uc?export=download&id=1VzuidR6VP7lmJpURCCLsmb5Lr4p9Xm8l).

**Comment by agouy** [comment]
1.4.2 to be validated

**Comment by makostadima** [comment]
Tried again to upload the .zip file using FCS 1.4.2 on Tercen.com.

I got the following error:

![image](https://user-images.githubusercontent.com/1746464/199456114-76964de3-9d66-4ff6-b858-1d533266c434.png)

**Comment by agouy** [comment]
@makostadima This should be fixed in 1.5.2

**Comment by makostadima** [comment]
@agouy did you mean to write 1.5.1?

If that's the case, I tested 1.5.1 and this time I got this error:

![image](https://user-images.githubusercontent.com/1746464/199498203-cd214ebc-807d-49ea-a0f2-64a72cf42bbc.png)

**Comment by makostadima** [comment]
I belive that we can now close this issue as we figured out that the problem is different and has been reported separately here: #11
