### ISSUE TITLE
Compensation matrices not output when setting output.compensation option to TRUE

### ISSUE THREAD

**Issue by makostadima** [tercen/read_fcs_operator#8]
This is the dataset I tried the operator on: https://drive.google.com/uc?export=download&id=1p9yTMu-NXIOwjJsY0vaa3vLeaBVOaT97

I used the FCS 1.4.1 setting both settings (use.descriptions and output.compensation) to TRUE and then the FCS 1.3.3 again with both settings TRUE.

[Here](https://tercen.com/myrto.kostadima/w/41fcacecf20de12dea7c2421179d27ca/ds/e97135e0-62aa-4571-bdba-9c1e23a74bf3) you see that the FCS.1.3.3 read dataset is compensated compared to the FCS1.4.1 read dataset. That means that the FCS file contains a compensation matrix.

When I then try to compensate the FCS 1.4.1 read dataset [here](https://tercen.com/myrto.kostadima/w/41fcacecf20de12dea7c2421179d27ca/ds/934bb25d-83a9-4d2a-9f82-d34499bd063c), I don't seem to be having a compensation matrices factor available, depsited having set the output.compensation setting to TRUE when reading the dataset.

This issue could be related to: #6.

**Comment by agouy** [comment]
1.4.2 to be validated

**Comment by makostadima** [comment]
Same issue with FCS 1.4.2 https://tercen.com/myrto.kostadima/w/41fcacecf20de12dea7c2421179d27ca/ds/934bb25d-83a9-4d2a-9f82-d34499bd063c

The compensation matrix isn't available in the list of factors after reading the file successfully.

**Comment by agouy** [comment]
@makostadima Read FCS 1.5.1 outputs the compensation matrices as a file in the project. This should be fixed now. I will provide a demo workflow
