### ISSUE TITLE
No spillover matrix stored in that sample error

### ISSUE THREAD

**Issue by fnaji** [tercen/read_fcs_operator#9]
When using this [dataset](https://drive.google.com/file/d/1E2ywR7q4qTWVgsFkpy3OomKLFjtH5wkA/view?usp=share_link), and selecting "output. compensation = true"  an error saying the following.

Failed to run operator, exit code = 1 --ERR-- WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. Error in .local(x, ...) : No spillover matrix stored in that sample Calls: %>% ... tryCatch -> tryCatchList -> tryCatchOne ->

**Comment by fnaji** [comment]
I think this dataset has no compensation matrix, so trying to apply compensation causes an error.

**Comment by agouy** [comment]
@fnaji shall we output no compensation even if output.compensation is set to true?
